
name: Deploy to Remote react-app-Server in OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build


    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa



    - name: Set up server.key file
      env: 
        SERVER_KEY: ${{secrets.SERVER_KEY}}
      run:
        echo "$SERVER_KEY" > ~/work/moviestreamingClient/moviestreamingClient/server.key
        chmod 600 ~/work/moviestreamingClient/moviestreamingClient/server.key



    - name: Set up server.crt file
      env: 
        SERVER_CERTIFICATE: ${{secrets.SERVER_CERTIFICATE}}
      run:
          echo "$SERVER_CERTIFICATE" > ~/work/moviestreamingClient/moviestreamingClient/server.crt
          chmod 600 ~/work/moviestreamingClient/moviestreamingClient/server.crt



    - name: Add remote server to known hosts
      run: |
        ssh-keyscan -v 155.248.245.222 >> ~/.ssh/known_hosts



    - name: Sync files to remote server
      run: |
        rsync -avz --delete-after ./dist/ opc@155.248.245.222:/home/opc/moviestreamingClient